service: ServerlessTestV4

provider:
  name: aws
  profile: personal_aws
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - sqs:CreateQueue
         - sqs:SendMessage
         - sqs:ReceiveMessage
         - sqs:DeleteMessage
         - sqs:GetQueueAttributes
         - sns:Publish
         - sns:CreateTopic
         - lambda:Invoke
         - cloudwatch:PutEvents
       Resource: "*"
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  environment:
    SQS_URL: ${file(./serverless.env.yml):dev.SQS_URL}
    SNS_ARN: ${file(./serverless.env.yml):dev.SNS_ARN}
    EVENT_ENDPOINT: ${file(./serverless.env.yml):dev.EVENT_ENDPOINT}

package:
  exclude:
    - node_modules/**
    - functions/play/**

functions:
  postmarkWebhookSqs:
    handler: functions/postmarkWebhookSqs/postmarkWebhookSqs.handler
    events:
      - http:
          path: webhook_to_sqs
          method: post

  sqsToEventGateway:
    handler: functions/sqsToEventGateway/sqsToEventGateway.handler
    events:
      - sns: LambdaTrigger
      - schedule: rate(24 hours)

resources:
  Resources:
    PostmarkWebhookQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PostmarkWebhookQueue

plugins:
  - serverless-offline
