service: ServerlessTestV4

provider:
  name: aws
  profile: default
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - sqs:CreateQueue
         - sqs:SendMessage
         - sqs:ReceiveMessage
         - sqs:DeleteMessage
         - sqs:GetQueueAttributes
         - sns:Publish
         - sns:CreateTopic
         - lambda:Invoke
         - cloudwatch:PutEvents
       Resource: "*"
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  environment:
    FOO: bar
    SQS_URL: ${file(./serverless.env.yml):dev.SQS_URL}
    SNS_ARN: ${file(./serverless.env.yml):dev.SNS_ARN}
    EVENT_ENDPOINT: ${file(./serverless.env.yml):dev.EVENT_ENDPOINT}

package:
  exclude:
    - node_modules/**
    - functions/play/**

functions:
  postmarkWebhookSqs:
    handler: functions/postmarkWebhookSqs/postmarkWebhookSqs.handler
    events:
      - http:
          path: webhook_to_sqs
          method: post

  sqsToEventGateway:
    handler: functions/sqsToEventGateway/sqsToEventGateway.handler
    events:
      - sns: Trigger6
      - schedule: rate(30 minutes)

resources:
  Resources:
    PostmarkWebhookQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PostmarkWebhookQueue
    
    Trigger6:
      Type: AWS::SNS::Topic
      Properties: 
        DisplayName: Trigger6
